# Workflow to publish Godot HTML5 games to GitHub Pages
#
# This script assumes that the project itself is in a subdirectory "project". This 
# folder structure frees up the root of the repository to be used for non-project
# files, such as the README, build folder, or raw assets folder.
#
# Make sure your project is configured for Web export
# to the path `build/web`.

name: 'Publish to GitHub Pages'

env:
  GODOT_VERSION: 4.3 # Remember to manually set image to this version below.

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: barichello/godot-ci:4.3

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Move HTML5 templates into position
        run: |
          ls -a /root/.local/share/godot/
          # wget https://github.com/godotengine/godot-builds/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
          # unzip Godot_v4.3-stable_export_templates.tpz
          ls -a /root/.local/share/godot/export_templates
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          # mv ~/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          # mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Create staging directory
        run: mkdir -v -p build/web

      - name: Build
        run: godot --headless --verbose --export-release "Web" build/web/index.html project/project.godot

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          user_name: 'github-ci[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish to gh-pages'

